[metadata]
type = "profile"
name = "Go profile"
author = "Mini-Qussa"
version = "Test"
linux_supported = true
windows_supported = true

[[targets]]
os = "windows"
arch = "amd64"
size = 14528900
checksum = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
branche = "main"
path = "windows/go-profile.toml"

[[targets]]
os = "linux"
arch = "amd64"
size = 12450112
checksum = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
branche = "main"
path = "linux/go-progile.toml"
